/* Main1.java
 * Modify Marshal 	Demonstrates how to modify a Java content tree.
 * C:\D-PA\programs\java\2016\JAXB_ri\jaxb-ri-2.2.11\jaxb-ri\samples\
 * SEE: https://docs.oracle.com/javase/tutorial/jaxb/intro/examples.html
 * 
 *  // This sample application demonstrates how to modify a java content
 *  // tree and marshal it back to a xml data
 * 2016-06-28 TOIMII!!
 * jaxb-ri\samples\modify-marshal example explained in 
 * https://docs.oracle.com/javase/tutorial/jaxb/intro/basic.html#bnbaz
 *
 * JAXB examples from:(https://docs.oracle.com/javase/tutorial/jaxb/intro/examples.html) 
 * 
 * Sample CODE from JAXB_RI loaded from: https://jaxb.java.net/
 * 
 * 2016-06-27
 * JAXB examples from
 * (https://docs.oracle.com/javase/tutorial/jaxb/intro/examples.html) 
 * utilize jaxb_ri loaded from: https://jaxb.java.net/
 * and stored into C:\D-PA\programs\java\2016\JAXB_ri\jaxb-ri-2.2.11\jaxb-ri
 * HUOM:
 * Lähdekooditiedostot (primer.po package) generoidaan ANT työkalulla (ks. readmePA.txt)
 * 
 * NOTE: primer.po packages have been added with a number suffix primer.po1.
 * in order to distinguish different examples.
 * Number Suffix also in Main classes
 * --------------------------------------------------
 */
 

package primer.po1;

import java.io.FileInputStream;
import java.io.IOException;
import java.math.BigDecimal;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

// import java content classes generated by binding compiler
import primer.po1.*;

/*
 * $Id: Main.java,v 1.1 2007-12-05 00:49:33 kohsuke Exp $
 */
 
public class Main1 {
    
    // This sample application demonstrates how to modify a java content
    // tree and marshal it back to a xml data
    
    public static void main( String[] args ) {
        try {
            // create a JAXBContext capable of handling classes generated into
            // the primer.po package
            JAXBContext jc = JAXBContext.newInstance( "primer.po1" ); //"primer.po"
            
            // create an Unmarshaller
            Unmarshaller u = jc.createUnmarshaller();
            
            // unmarshal a po instance document into a tree of Java content
            // objects composed of classes from the primer.po package.
            JAXBElement poe = 
                (JAXBElement)u.unmarshal( new FileInputStream( "src/primer/po1/po.xml" ) ); //"po.xml"
	    PurchaseOrderType po = (PurchaseOrderType)poe.getValue();

            // change the billto address
            USAddress address = po.getBillTo();
            address.setName( "John Bob" );
            address.setStreet( "242 Main Street" );
            address.setCity( "Beverly Hills" );
            address.setState( "CA" );
            address.setZip( new BigDecimal( "90210" ) );
            
            // create a Marshaller and marshal to a file
            Marshaller m = jc.createMarshaller();
            m.setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE );
            m.marshal( poe, System.out );
            
        } catch( JAXBException je ) {
            je.printStackTrace();
        } catch( IOException ioe ) {
            ioe.printStackTrace();
        }
    }
}
