//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:06:11 PM EEST 
//


package siima.machine3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import primer.po2.USAddress;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the siima.machine2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Machine_QNAME = new QName("", "Machine");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: siima.machine2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MachineType }
     * 
     */
    public MachineType createMachineType() {
        return new MachineType();
    }

    /*
     * VPA: ADDED
     */
    
    public Component createComponent() {
        return new Component();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MachineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Machine")
    public JAXBElement<MachineType> createMachine(MachineType value) {
        return new JAXBElement<MachineType>(_Machine_QNAME, MachineType.class, null, value);
    }

}
