//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 10:55:11 AM EEST 
//


package primer.myPo3;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, Short>
{


    public Short unmarshal(String value) {
        return (primer.myPo3.MyDatatypeConverter.parseIntegerToShort(value));
    }

    public String marshal(Short value) {
        return (primer.myPo3.MyDatatypeConverter.printShortToInteger(value));
    }

}
