//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 10:55:11 AM EEST 
//


package primer.myPo3;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Integer>
{


    public Integer unmarshal(String value) {
        return (primer.myPo3.MyDatatypeConverter.parseIntegerToInt(value)); //primer.MyDatatypeConverter.parseIntegerToInt(value)
    }

    public String marshal(Integer value) {
        return (primer.myPo3.MyDatatypeConverter.printIntToInteger(value));
    }

}
